2025-03-28 00:37:13,009 INFO    MainThread:18401 [wandb_setup.py:_flush():67] Current SDK version is 0.19.8
2025-03-28 00:37:13,011 INFO    MainThread:18401 [wandb_setup.py:_flush():67] Configure stats pid to 18401
2025-03-28 00:37:13,011 INFO    MainThread:18401 [wandb_setup.py:_flush():67] Loading settings from /root/.config/wandb/settings
2025-03-28 00:37:13,012 INFO    MainThread:18401 [wandb_setup.py:_flush():67] Loading settings from /content/drive/MyDrive/Tesis/Tesis/Codigo/wandb/settings
2025-03-28 00:37:13,012 INFO    MainThread:18401 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-28 00:37:13,013 INFO    MainThread:18401 [wandb_init.py:setup_run_log_directory():647] Logging user logs to ./wandb/run-20250328_003712-w3xyig8m/logs/debug.log
2025-03-28 00:37:13,013 INFO    MainThread:18401 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to ./wandb/run-20250328_003712-w3xyig8m/logs/debug-internal.log
2025-03-28 00:37:13,013 INFO    MainThread:18401 [wandb_init.py:init():761] calling init triggers
2025-03-28 00:37:13,013 INFO    MainThread:18401 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'dataset': {'data_scaling': True, 'batch_sizes': {'stage1': 32, 'stage2': 32, 'stage_neural_mapper': 32}, 'num_workers': 0}, 'exp_params': {'lr': 0.005, 'linear_warmup_rate': 0.05, 'min_lr': 0.0001}, 'trainer_params': {'max_steps': {'stage1': 20000, 'stage2': 40000, 'stage_neural_mapper': 3000}, 'val_check_interval': {'stage1': 1, 'stage2': 1000, 'stage_neural_mapper': 1000}}, 'encoder': {'init_dim': 4, 'hid_dim': 128, 'n_resnet_blocks': 2, 'downsampled_width': {'lf': 8, 'hf': 32}}, 'decoder': {'n_resnet_blocks': 2}, 'VQ-VAE': {'latent_dim': 64, 'codebook_size': 256, 'kmeans_init': True, 'codebook_dim': 8}, 'MaskGIT': {'choice_temperatures': {'lf': 10, 'hf': 0}, 'T': {'lf': 10, 'hf': 10}, 'prior_model_l': {'hidden_dim': 128, 'n_layers': 4, 'heads': 2, 'ff_mult': 1, 'use_rmsnorm': True, 'p_unconditional': 0.2, 'model_dropout': 0.3, 'emb_dropout': 0.3}, 'prior_model_h': {'hidden_dim': 32, 'n_layers': 1, 'heads': 1, 'ff_mult': 1, 'use_rmsnorm': True, 'p_unconditional': 0.2, 'model_dropout': 0.3, 'emb_dropout': 0.3}, 'cfg_scale': 1.0, 'ESS': {'use': False, 'error_ratio_ma_rate': 0.3}}, 'neural_mapper': {'dim': 8, 'dim_mults': [1, 2, 4, 8], 'resnet_block_groups': 4, 'dropout': 0.5, 'tau_search_rng': [0.1, 0.5, 1, 2, 4]}, 'evaluation': {'batch_size': 32, 'min_num_gen_samples': 1024}, 'dataset_path': '/content/drive/MyDrive/Tesis/Tesis/Codigo/TimeVQVAE/supernova_light_curves_1.csv', 'n_trainable_params': 57900, '_wandb': {}}
2025-03-28 00:37:13,013 INFO    MainThread:18401 [wandb_init.py:init():784] starting backend
2025-03-28 00:37:13,014 INFO    MainThread:18401 [wandb_init.py:init():788] sending inform_init request
2025-03-28 00:37:13,019 INFO    MainThread:18401 [backend.py:_multiprocessing_setup():101] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2025-03-28 00:37:13,019 INFO    MainThread:18401 [wandb_init.py:init():798] backend started and connected
2025-03-28 00:37:13,023 INFO    MainThread:18401 [wandb_init.py:init():891] updated telemetry
2025-03-28 00:37:13,130 INFO    MainThread:18401 [wandb_init.py:init():915] communicating run to backend with 90.0 second timeout
2025-03-28 00:37:13,821 INFO    MainThread:18401 [wandb_init.py:init():990] starting run threads in backend
2025-03-28 00:37:14,537 INFO    MainThread:18401 [wandb_run.py:_console_start():2375] atexit reg
2025-03-28 00:37:14,538 INFO    MainThread:18401 [wandb_run.py:_redirect():2227] redirect: wrap_raw
2025-03-28 00:37:14,538 INFO    MainThread:18401 [wandb_run.py:_redirect():2292] Wrapping output streams.
2025-03-28 00:37:14,538 INFO    MainThread:18401 [wandb_run.py:_redirect():2315] Redirects installed.
2025-03-28 00:37:14,540 INFO    MainThread:18401 [wandb_init.py:init():1032] run started, returning control to user process
2025-03-28 00:50:58,182 INFO    MsgRouterThr:18401 [mailbox.py:close():129] Closing mailbox, abandoning 1 handles.
2025-03-28 00:51:00,677 ERROR   MainThread:18401 [redirect.py:_on_write():661] error in stdout callback
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/usr/local/lib/python3.11/dist-packages/wandb/sdk/wandb_run.py", line 2296, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/usr/local/lib/python3.11/dist-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/usr/local/lib/python3.11/dist-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/usr/local/lib/python3.11/dist-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/usr/local/lib/python3.11/dist-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/usr/local/lib/python3.11/dist-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/usr/local/lib/python3.11/dist-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/usr/local/lib/python3.11/dist-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-03-28 00:51:00,696 ERROR   MainThread:18401 [redirect.py:_on_write():661] error in stdout callback
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/usr/local/lib/python3.11/dist-packages/wandb/sdk/wandb_run.py", line 2296, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/usr/local/lib/python3.11/dist-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/usr/local/lib/python3.11/dist-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/usr/local/lib/python3.11/dist-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/usr/local/lib/python3.11/dist-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/usr/local/lib/python3.11/dist-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/usr/local/lib/python3.11/dist-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/usr/local/lib/python3.11/dist-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-03-28 00:51:00,702 ERROR   MainThread:18401 [redirect.py:_on_write():661] error in stdout callback
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/usr/local/lib/python3.11/dist-packages/wandb/sdk/wandb_run.py", line 2296, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/usr/local/lib/python3.11/dist-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/usr/local/lib/python3.11/dist-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/usr/local/lib/python3.11/dist-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/usr/local/lib/python3.11/dist-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/usr/local/lib/python3.11/dist-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/usr/local/lib/python3.11/dist-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/usr/local/lib/python3.11/dist-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-03-28 00:51:00,703 ERROR   MainThread:18401 [redirect.py:_on_write():661] error in stdout callback
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/usr/local/lib/python3.11/dist-packages/wandb/sdk/wandb_run.py", line 2296, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/usr/local/lib/python3.11/dist-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/usr/local/lib/python3.11/dist-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/usr/local/lib/python3.11/dist-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/usr/local/lib/python3.11/dist-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/usr/local/lib/python3.11/dist-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/usr/local/lib/python3.11/dist-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/usr/local/lib/python3.11/dist-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-03-28 00:51:00,703 ERROR   MainThread:18401 [redirect.py:_on_write():661] error in stdout callback
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/usr/local/lib/python3.11/dist-packages/wandb/sdk/wandb_run.py", line 2296, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/usr/local/lib/python3.11/dist-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/usr/local/lib/python3.11/dist-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/usr/local/lib/python3.11/dist-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/usr/local/lib/python3.11/dist-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/usr/local/lib/python3.11/dist-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/usr/local/lib/python3.11/dist-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/usr/local/lib/python3.11/dist-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-03-28 00:51:00,704 ERROR   MainThread:18401 [redirect.py:_on_write():661] error in stdout callback
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/usr/local/lib/python3.11/dist-packages/wandb/sdk/wandb_run.py", line 2296, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/usr/local/lib/python3.11/dist-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/usr/local/lib/python3.11/dist-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/usr/local/lib/python3.11/dist-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/usr/local/lib/python3.11/dist-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/usr/local/lib/python3.11/dist-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/usr/local/lib/python3.11/dist-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/usr/local/lib/python3.11/dist-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
